"""Add Movie Rating model

Revision ID: 8940320ce722
Revises: ab9313a58f07
Create Date: 2026-06-30 00:52:10.566092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8940320ce722'
down_revision: Union[str, Sequence[str], None] = 'ab9313a58f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "movie_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "movie_id",
            name="uq_user_movie_rating",
        ),
    )

    op.create_index(
        "ix_movie_ratings_movie_id",
        "movie_ratings",
        ["movie_id"],
        unique=False,
    )

    op.add_column(
        "movies",
        sa.Column(
            "average_rating",
            sa.Numeric(3, 2),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "movies",
        sa.Column(
            "ratings_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'ratings_count')
    op.drop_column('movies', 'average_rating')
    op.drop_index('ix_movie_ratings_movie_id', table_name='movie_ratings')
    op.drop_table('movie_ratings')
    # ### end Alembic commands ###
