"""Add Movie Comments and Comment likes models

Revision ID: fa65bec69b20
Revises: 8940320ce722
Create Date: 2026-06-30 14:25:17.884329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa65bec69b20'
down_revision: Union[str, Sequence[str], None] = '8940320ce722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('replies_count', sa.Integer(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['movie_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_comments_movie_id'), 'movie_comments', ['movie_id'], unique=False)
    op.create_index('ix_movie_comments_movie_parent', 'movie_comments', ['movie_id', 'parent_comment_id'], unique=False)
    op.create_index(op.f('ix_movie_comments_parent_comment_id'), 'movie_comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_movie_comments_user', 'movie_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_movie_comments_user_id'), 'movie_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_movie_comments_uuid'), 'movie_comments', ['uuid'], unique=True)
    op.create_table('movie_comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['movie_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', name='uq_user_comment_like')
    )
    op.create_index(op.f('ix_movie_comment_likes_comment_id'), 'movie_comment_likes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_movie_comment_likes_user_id'), 'movie_comment_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_comment_likes_user_id'), table_name='movie_comment_likes')
    op.drop_index(op.f('ix_movie_comment_likes_comment_id'), table_name='movie_comment_likes')
    op.drop_table('movie_comment_likes')
    op.drop_index(op.f('ix_movie_comments_uuid'), table_name='movie_comments')
    op.drop_index(op.f('ix_movie_comments_user_id'), table_name='movie_comments')
    op.drop_index('ix_movie_comments_user', table_name='movie_comments')
    op.drop_index(op.f('ix_movie_comments_parent_comment_id'), table_name='movie_comments')
    op.drop_index('ix_movie_comments_movie_parent', table_name='movie_comments')
    op.drop_index(op.f('ix_movie_comments_movie_id'), table_name='movie_comments')
    op.drop_table('movie_comments')
    # ### end Alembic commands ###
